#!/bin/sh
#
# Build ~/.config/i3/config from the shared ~/.config/i3/config.base and, if it
# exists, ~/.config/i3/<hostname>.conf.
#
# i3 only gained an `include` directive in 4.20 and some machines run older
# versions, so the two files are joined here instead. The host file goes last:
# a later for_window or exec adds to the shared ones. A variable the host file
# sets replaces the shared definition rather than duplicating it, which is how
# a machine picks its own $term. A host file must not rebind a key the shared
# file already binds; i3 rejects duplicate bindings.
#
# With --restart, restart i3 when the generated file changed. The i3 config
# runs this on every start and restart, so editing either source file and
# pressing $mod+Shift+r is enough. The second pass finds nothing to change and
# stops there.

dir="$HOME/.config/i3"
base="$dir/config.base"
host="$dir/$(hostname -s).conf"
out="$dir/config"

[ -r "$base" ] || { echo "i3-build-config.sh: $base not found" >&2; exit 1; }

tmp=$(mktemp "$dir/config.XXXXXX") || exit 1
trap 'rm -f "$tmp"' EXIT

{
  echo "# GENERATED by ~/.bin/i3-build-config.sh. Do not edit: changes are"
  echo "# overwritten. Edit config.base or $(hostname -s).conf instead."
  echo
  if [ -r "$host" ]; then
    # Pass 1 collects the variables the host file sets; pass 2 prints the
    # shared file without its definitions of those variables.
    awk 'NR == FNR { if ($1 == "set") host[$2] = 1; next }
         $1 == "set" && ($2 in host) { next }
         { print }' "$host" "$base"
    echo
    echo "# ---- from $(hostname -s).conf ----"
    cat "$host"
  else
    cat "$base"
  fi
} >"$tmp"

if cmp -s "$tmp" "$out"; then
  exit 0
fi

mv "$tmp" "$out"
[ "${1:-}" = "--restart" ] && i3-msg restart >/dev/null 2>&1
exit 0
